# -*- coding: utf-8 -*-
"""SIstem Pakar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9XbFpT4ksCD20-eAcnQCw2RmW3neDLP
"""

def identifikasi_hama(daun_menguning, bercak_hitam, daun_berlubang, tanaman_layu):
    if daun_menguning and tanaman_layu:
        return "Hama Aphids"
    elif daun_menguning and bercak_hitam:
        return "Jamur Daun"
    elif bercak_hitam and daun_berlubang:
        return "Hama Ulat"
    elif daun_berlubang and tanaman_layu:
        return "Hama Kumbang"
    else:
        return "Hama tidak diketahui, perlu pemeriksaan lanjut"

# Contoh penggunaan
gejala = {
    "daun_menguning": True,
    "bercak_hitam": False,
    "daun_berlubang": False,
    "tanaman_layu": True
}

hasil = identifikasi_hama(**gejala)
print("Jenis Hama:", hasil)